### PR TITLE
i18n

### PR DESCRIPTION
**Pull request by senlin**
Referring to our earlier talk on [the topic of internationalisation](https://github.com/factmaven/disable-blogging/pull/2#issuecomment-248142943), I finally found the time to do this.

### CODE REVIEW

**Comment by houseraevan** [comment]
Thanks @senlin for the update! As I understand, this allows the plugin to be translatable? The next step is to then add the language folder and translated files, right?

**Comment by senlin** [comment]
You're welcome :) It indeed allows the plugin to be fully translatable. Adding translations are no longer necessary as translations are now served via [Translating WordPress](https://translate.wordpress.org/projects/wp-plugins/disable-blogging). But I have added the language folder and generated a pot file.

I have just added a few more files to this PR that deal with changing the text domain in the main plugin file, adding the function that loads the translation file and adding the .pot file

**Comment by sectsect** [comment]
@senlin 
Thanks for your great job👏🏻

@factmaven 
I'm ready to add the Japanese translation files.
If you need other language to test, I will submit a "pull request".

**Comment by houseraevan** [comment]
Sounds great @senlin, this is very new and exciting for me. I'll go through the code so I can understand what you've done and merge your changes for the next update.

Thank @sectsect, feel free to go ahead with adding a Japanese translation. I'm going to push the changes that @senlin made so that it's properly prepared for localization. This way Japanese can be the first language it is translated in!

**Comment by senlin** [comment]
Cool to hear it's exciting for you @factmaven :) 
If you have any questions, please let me know.

**Comment by sectsect** [comment]
Hi @factmaven 

Can you make a other `branch` from @senlin 's `pull request`?

CC: @senlin

**Comment by houseraevan** [comment]
@sectsect: I current have a [`dev`](https://github.com/factmaven/disable-blogging/tree/dev) branch for any new and upcoming changes. This would be the ideal place to pull the changes until everything is finalized and pushed to `master`.

@senlin: Please change the pull request to our `dev` branch. According to [this post](http://stackoverflow.com/a/9136246/6579923), I cannot change the merge request to the `dev` brand on my end. This way, no changes are made to the `master` until everything is finalized.

**Comment by senlin** [comment]
I'm afraid I don't have time for that at the moment.
Easiest is to accept my PR, then merge it into your dev branch and then make clear that all further PRs are to be committed to that dev branch.

**Comment by houseraevan** [comment]
No worries, I'll do that. Thanks.

**Comment by houseraevan** [comment]
Merged, thanks.

**Pull request merged**
