### PR TITLE
Add filter to move Pages up the top in the sidebar menu

### PR DESCRIPTION
**Pull request by senlin**
Great plugin!
I have added a filter that adjusts the (sidebar) menu order. Since Posts are no longer in the equation I think it is safe to assume that Pages are more important for the user that installs your plugin. The filter in this PR moves the edit Pages menu up.
Cheers,
Piet

### CODE REVIEW

**Comment by houseraevan** [comment]
Hi @senlin 

That's an excellent idea. This will definitely improve the user experience by reprioritizing the _Pages_ menu. Especially if this plugin is used by a web developer for their client's website and they aren't familiar with the navigation in the _Dashboard_.

This will be implemented in the next update with credit given to your of course. Thank you.

Also, you're the first person to contribute to this plugin! If you have more ideas on how to improve this plugin, be sure to send them our way.

**Review by ghost — APPROVED** [review]

**Comment by senlin** [comment]
Thanks for the merge @factmaven 

In fact I have a few more ideas to improve the plugin, i18n being one of them :) Will send you a PR once I have gotten around to implement that in my fork.

**Comment by houseraevan** [comment]
@senlin Of course.

Implementing `i18n` is a great idea. You'll definitely do a better job at it with your [WPML background](https://so-wp.com/wpml-implementation/).

I'm working on a new and improved version 2.0.0 which you can [find it in the `dev` branch](https://github.com/factmaven/disable-blogging/tree/dev). It's rebuilt with a new Settings API wrapper so everything is now 100% customizable.

It's not done yet, but I've recently migrated all of the functions to the new 2.0.0

**Comment by senlin** [comment]
Cool, I will fork the dev branch then and use that for i18n implementation :)

**Comment by houseraevan** [comment]
@senlin Excellent, Looking forward to it.

**Pull request merged**
